### PR TITLE
have you tried this?

### PR DESCRIPTION
**Pull request by kenman345**
try this one out

### CODE REVIEW

**Comment by lillypad** [comment]
Hey @kenman345 that's really nice of you to make a `PR`.

I was going to be adding this in however been to busy with other work.

I really appreciate it, and will see how the checks run this time.

Are you an emacs user as well?

**Comment by kenman345** [comment]
Nope, I just have been messing with Travis-Ci a lot. Hopefully this works better.

Seems I was right to make it one stage as one of those builds taking forever

**Comment by kenman345** [comment]
I made another set of small changes. Sorry that it will force another build but I figured its always best to follow best practices for YML files. When you only have one item in a list, you can disregard using a dash infront of it. This makes it be evaluated as a single entry and not an array of just 1 entry, making it get parsed better by Travis. I put comments in to help if changes are made in the future

**Comment by kenman345** [comment]
It would appear to me that you may be missing some emacs before-install steps and according to my research `language: emacs-lisp` may no longer be supported or do anything?

**Comment by lillypad** [comment]
@kenman345 I'll give this a shot in a little while i do believe `emacs-lisp` is probably not supported anymore. The longest build is for Gentoo which makes sense.

**Comment by lillypad** [comment]
Looks like all these go through except for Mac OS X which is to be expected I'm still working on `brew install` for this. I will commit these changes to the yaml you made as soon as I fix the Mac OS build test.

**Comment by lillypad** [comment]
Na I'll merge it now because that's broken anyway it's the `develop` branch so shouldn't matter too much.

**Comment by kenman345** [comment]
Just wanted to also add, that you are not doing anything terribly special with Travis-CI that makes you need build stages, if your `.travis.yml` wereto not use stages and instead just use matrix expansion instead of job expansion, you would be able to get `fast_finish: true` and then when one of your builds fails, like the OSX one, then it would mark the build failed but continue finishing up any of the already started jobs.

```yml
sudo: required

language: emacs-lisp

os: linux

services:
  docker # add a dash before this if you add another service in the future 

matrix:
  fast_finish: true
  include:
    - script: docker build -f docker/ubuntu/Dockerfile .
    - script: docker build -f docker/debian/Dockerfile .
    - script: docker build -f docker/arch/Dockerfile .
    - script: docker build -f docker/gentoo/Dockerfile .
    - os: osx
      script: make osx
```

**Pull request merged**
